name: MyTest 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:   # allows manual run

jobs:
  build:
    runs-on: windows-latest   # works with your Windows setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build

    - name: Publish
      run: dotnet publish -c Release -o ./publish
